# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/Xilinx/Project/200t/Quadrature_Demodulation/Quadrature_Demodulation.xdc

# IP: ip/fir_compiler_2/fir_compiler_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fir_compiler_2 || ORIG_REF_NAME==fir_compiler_2} -quiet] -quiet

# IP: ip/fifo_generator_fft/fifo_generator_fft.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_generator_fft || ORIG_REF_NAME==fifo_generator_fft} -quiet] -quiet
