# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Xilinx/Project/200t/Quadrature_Demodulation/Quadrature_Demodulation.srcs/sources_1/ip/c_add_0/c_add_0.xci
# IP: The module: 'c_add_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Xilinx/Project/200t/Quadrature_Demodulation/Quadrature_Demodulation.gen/sources_1/ip/c_add_0/c_add_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'c_add_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/Xilinx/Project/200t/Quadrature_Demodulation/Quadrature_Demodulation.srcs/sources_1/ip/c_add_0/c_add_0.xci
# IP: The module: 'c_add_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Xilinx/Project/200t/Quadrature_Demodulation/Quadrature_Demodulation.gen/sources_1/ip/c_add_0/c_add_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'c_add_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
