# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "D:/Xilinx/Project/200t/Quadrature_Demodulation/.Xil/Vivado-3300-Blessing/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7a200tfbg484-1
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    D:/Xilinx/Project/200t/Quadrature_Demodulation/Quadrature_Demodulation.srcs/sources_1/ip/fifo_generator_0
    D:/Xilinx/Project/200t/Quadrature_Demodulation/Quadrature_Demodulation.srcs/sources_1/ip/dds_compiler_1
    D:/Xilinx/Project/200t/Quadrature_Demodulation/Quadrature_Demodulation.srcs/sources_1/ip/mult_gen_0
    D:/Xilinx/Project/200t/Quadrature_Demodulation/Quadrature_Demodulation.srcs/sources_1/ip/fir_compiler_1
    D:/Xilinx/Project/200t/Quadrature_Demodulation/Quadrature_Demodulation.srcs/sources_1/ip/bram_16x2048
    D:/Xilinx/Project/200t/Quadrature_Demodulation/Quadrature_Demodulation.srcs/sources_1/ip/mult_gen_1
    D:/Xilinx/Project/200t/Quadrature_Demodulation/Quadrature_Demodulation.srcs/sources_1/ip/c_add_0
    D:/Xilinx/Project/200t/Quadrature_Demodulation/Quadrature_Demodulation.srcs/sources_1/ip/cordic_0
    D:/Xilinx/Project/200t/Quadrature_Demodulation/Quadrature_Demodulation.srcs/sources_1/ip/cic_14BITS_1250
    D:/Xilinx/Project/200t/Quadrature_Demodulation/Quadrature_Demodulation.srcs/sources_1/ip/clk_wiz_0
    D:/Xilinx/Project/200t/Quadrature_Demodulation/Quadrature_Demodulation.srcs/sources_1/ip/xfft_0
    D:/Xilinx/Project/200t/Quadrature_Demodulation/Quadrature_Demodulation.srcs/sources_1/ip/cic_compiler_0
    D:/Xilinx/Project/200t/Quadrature_Demodulation/Quadrature_Demodulation.srcs/sources_1/ip/fir_compiler_2
    D:/Xilinx/Project/200t/Quadrature_Demodulation/Quadrature_Demodulation.srcs/sources_1/ip/cic_compiler_16bit
  } {
      D:/Xilinx/Vivado/2023.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      D:/Xilinx/Vivado/2023.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -include {
    D:/Xilinx/Project/200t/Quadrature_Demodulation/Quadrature_Demodulation.srcs/sources_1/ip/fifo_generator_0
    D:/Xilinx/Project/200t/Quadrature_Demodulation/Quadrature_Demodulation.srcs/sources_1/ip/dds_compiler_1
    D:/Xilinx/Project/200t/Quadrature_Demodulation/Quadrature_Demodulation.srcs/sources_1/ip/mult_gen_0
    D:/Xilinx/Project/200t/Quadrature_Demodulation/Quadrature_Demodulation.srcs/sources_1/ip/fir_compiler_1
    D:/Xilinx/Project/200t/Quadrature_Demodulation/Quadrature_Demodulation.srcs/sources_1/ip/bram_16x2048
    D:/Xilinx/Project/200t/Quadrature_Demodulation/Quadrature_Demodulation.srcs/sources_1/ip/mult_gen_1
    D:/Xilinx/Project/200t/Quadrature_Demodulation/Quadrature_Demodulation.srcs/sources_1/ip/c_add_0
    D:/Xilinx/Project/200t/Quadrature_Demodulation/Quadrature_Demodulation.srcs/sources_1/ip/cordic_0
    D:/Xilinx/Project/200t/Quadrature_Demodulation/Quadrature_Demodulation.srcs/sources_1/ip/cic_14BITS_1250
    D:/Xilinx/Project/200t/Quadrature_Demodulation/Quadrature_Demodulation.srcs/sources_1/ip/clk_wiz_0
    D:/Xilinx/Project/200t/Quadrature_Demodulation/Quadrature_Demodulation.srcs/sources_1/ip/xfft_0
    D:/Xilinx/Project/200t/Quadrature_Demodulation/Quadrature_Demodulation.srcs/sources_1/ip/cic_compiler_0
    D:/Xilinx/Project/200t/Quadrature_Demodulation/Quadrature_Demodulation.srcs/sources_1/ip/fir_compiler_2
    D:/Xilinx/Project/200t/Quadrature_Demodulation/Quadrature_Demodulation.srcs/sources_1/ip/cic_compiler_16bit
  } {
      D:/Xilinx/Project/200t/Quadrature_Demodulation/.Xil/Vivado-3300-Blessing/realtime/fifo_generator_fft_stub.v
      D:/Xilinx/Project/200t/Quadrature_Demodulation/.Xil/Vivado-3300-Blessing/realtime/fifo_generator_0_stub.v
      D:/Xilinx/Project/200t/Quadrature_Demodulation/.Xil/Vivado-3300-Blessing/realtime/dds_compiler_1_stub.v
      D:/Xilinx/Project/200t/Quadrature_Demodulation/.Xil/Vivado-3300-Blessing/realtime/mult_gen_0_stub.v
      D:/Xilinx/Project/200t/Quadrature_Demodulation/.Xil/Vivado-3300-Blessing/realtime/fir_compiler_1_stub.v
      D:/Xilinx/Project/200t/Quadrature_Demodulation/.Xil/Vivado-3300-Blessing/realtime/bram_16x2048_stub.v
      D:/Xilinx/Project/200t/Quadrature_Demodulation/.Xil/Vivado-3300-Blessing/realtime/mult_gen_1_stub.v
      D:/Xilinx/Project/200t/Quadrature_Demodulation/.Xil/Vivado-3300-Blessing/realtime/c_add_0_stub.v
      D:/Xilinx/Project/200t/Quadrature_Demodulation/.Xil/Vivado-3300-Blessing/realtime/cordic_0_stub.v
      D:/Xilinx/Project/200t/Quadrature_Demodulation/.Xil/Vivado-3300-Blessing/realtime/cic_14BITS_1250_stub.v
      D:/Xilinx/Project/200t/Quadrature_Demodulation/.Xil/Vivado-3300-Blessing/realtime/clk_wiz_0_stub.v
      D:/Xilinx/Project/200t/Quadrature_Demodulation/.Xil/Vivado-3300-Blessing/realtime/xfft_0_stub.v
      D:/Xilinx/Project/200t/Quadrature_Demodulation/.Xil/Vivado-3300-Blessing/realtime/cic_compiler_0_stub.v
      D:/Xilinx/Project/200t/Quadrature_Demodulation/.Xil/Vivado-3300-Blessing/realtime/fir_compiler_2_stub.v
      D:/Xilinx/Project/200t/Quadrature_Demodulation/.Xil/Vivado-3300-Blessing/realtime/cic_compiler_16bit_stub.v
      D:/Xilinx/Project/200t/Quadrature_Demodulation/Quadrature_Demodulation.srcs/sources_1/new/AD_trans.v
      D:/Xilinx/Project/200t/Quadrature_Demodulation/Quadrature_Demodulation.srcs/sources_1/new/DA_trans.v
      D:/Xilinx/Project/200t/Quadrature_Demodulation/Quadrature_Demodulation.srcs/sources_1/new/DDS_FREQ_CONFIG.v
      D:/Xilinx/Project/200t/Quadrature_Demodulation/Quadrature_Demodulation.srcs/sources_1/new/Demodulation.v
      D:/Xilinx/Project/200t/Quadrature_Demodulation/Quadrature_Demodulation.srcs/sources_1/new/FFT.v
      D:/Xilinx/Project/200t/Quadrature_Demodulation/Quadrature_Demodulation.srcs/sources_1/new/FFT_NonRealTIME.v
      D:/Xilinx/Project/200t/Quadrature_Demodulation/Quadrature_Demodulation.srcs/sources_1/new/FM_DEMOD.v
      D:/Xilinx/Project/200t/Quadrature_Demodulation/Quadrature_Demodulation.srcs/sources_1/new/GET_Freq_FFT.v
      D:/Xilinx/Project/200t/Quadrature_Demodulation/Quadrature_Demodulation.srcs/sources_1/new/GET_LineNum_FFT.v
      D:/Xilinx/Project/200t/Quadrature_Demodulation/Quadrature_Demodulation.srcs/sources_1/new/GET_Max_Min_Med.v
      D:/Xilinx/Project/200t/Quadrature_Demodulation/Quadrature_Demodulation.srcs/sources_1/new/HS_AD9481_IN.v
      D:/Xilinx/Project/200t/Quadrature_Demodulation/Quadrature_Demodulation.srcs/sources_1/new/OUPUT_CHOSE.v
      D:/Xilinx/Project/200t/Quadrature_Demodulation/Quadrature_Demodulation.srcs/sources_1/new/SCAN_CONTROL.v
      D:/Xilinx/Project/200t/Quadrature_Demodulation/Quadrature_Demodulation.srcs/sources_1/new/UART.v
      D:/Xilinx/Project/200t/Quadrature_Demodulation/Quadrature_Demodulation.srcs/sources_1/new/mode_control.v
      D:/Xilinx/Project/200t/Quadrature_Demodulation/Quadrature_Demodulation.srcs/sources_1/new/uart_tx.v
      D:/Xilinx/Project/200t/Quadrature_Demodulation/Quadrature_Demodulation.srcs/sources_1/new/Quadrature_Demodulation.v
    }
      rt::read_vhdl -lib xpm D:/Xilinx/Vivado/2023.1/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top Quadrature_Demodulation
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter dataflowBusHighlighting false
    rt::set_parameter generateDataflowBusNetlist false
    rt::set_parameter dataFlowViewInElab false
    rt::set_parameter busViewFixBrokenConnections false
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "D:/Xilinx/Project/200t/Quadrature_Demodulation/.Xil/Vivado-3300-Blessing/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
