# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Xilinx/Project/200t/Quadrature_Demodulation/Quadrature_Demodulation.srcs/sources_1/ip/cic_compiler_16bit/cic_compiler_16bit.xci
# IP: The module: 'cic_compiler_16bit' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Xilinx/Project/200t/Quadrature_Demodulation/Quadrature_Demodulation.gen/sources_1/ip/cic_compiler_16bit/cic_compiler_16bit_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cic_compiler_16bit'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/Xilinx/Project/200t/Quadrature_Demodulation/Quadrature_Demodulation.srcs/sources_1/ip/cic_compiler_16bit/cic_compiler_16bit.xci
# IP: The module: 'cic_compiler_16bit' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Xilinx/Project/200t/Quadrature_Demodulation/Quadrature_Demodulation.gen/sources_1/ip/cic_compiler_16bit/cic_compiler_16bit_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cic_compiler_16bit'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
